### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by williamd1k0** [LucasFlicky/cogumelando-firefox#1]
# TODOs
- [x] Panel/popup basic `0.1.0`
- [x] Storage `0.1.0`
- [x] Panel/popup working `0.1.0`
- [x] Configs page basic `0.1.0`
- [x] Configs page working
- [x] AJAX test `0.1.0`
- [x] Notifications basic `0.1.0`
- [x] Alarms/timers basic
- [x] Chrome background implementation
- [x] Full implementation
- [x] Add HDPI icons
- [ ] Optimization
- [ ] Bug fixes

**Comment by williamd1k0** [comment]
@LucasFlicky Falta teus A7 só, enquanto eu faço uma revisão pra otimizar os coiso.
