### ISSUE TITLE
Config Page

### ISSUE THREAD

**Issue by williamd1k0** [LucasFlicky/cogumelando-firefox#2]
# TODOs
- [x] Configs page basic `0.1.0`
- [x] Implements Controller (DOM+Storage)
- [x] Check CSS
- [x] Configs page working
