### ISSUE TITLE
Panel Page (popup)

### ISSUE THREAD

**Issue by williamd1k0** [LucasFlicky/cogumelando-firefox#4]
# TODOs
- [x] Panel/popup basic `0.1.0`
- [x] Panel/popup working `0.1.0`
- [x] AJAX test `0.1.0`
- [x] On Stream implementation
